### ISSUE TITLE
[Bug]: Authentication not reporting back succesfull

### ISSUE THREAD

**Issue by brggmn** [giuseppecastaldo/ha-addons#130]
### The problem

I receive a QRcode to link whatsapp to my HomeAssistant. The QRcode is valid, and the addon states that the client is ready, however, the connection back to my Whatsapp seems to fail because it keeps showing the "logging in ..." screen. 
After some time (seconds, minute or 2), my whatsapp reports back: "Couldn't log in. Check your phone's internet connection and scan the QR code again." 
On this event, my addon log writes back that "default - Client default was logged out. Restarting..." and crashes. (see log output)

My phone has internet and linking whatsapp web on other browsers works flawlessly.

### What version of Home Assistant Core has the issue?

2025.10.4

### What version of the addon has the issue?

1.5.1

### What type of installation are you running?

Home Assistant OS

### Log information

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Whatsapp
 Whatsapp addon for send message from Home Assistant
-----------------------------------------------------------
 Add-on version: 1.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 16.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2025.11.0
 Home Assistant Supervisor: 2025.11.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:39:36] INFO: Installed custom component.
[2025-11-06T14:39:37.712] [INFO] default - Whatsapp Addon started.
[2025-11-06T14:39:38.100] [INFO] default - default require authentication over QRCode, please see your notifications...
[2025-11-06T14:39:47.366] [INFO] default - default client is ready.
[2025-11-06T14:40:48.032] [INFO] default - Client default was logged out. Restarting...
node:internal/fs/rimraf:59
    callback(err);
    ^
TypeError: callback is not a function
    at CB (node:internal/fs/rimraf:59:5)
    at FSReqCallback.oncomplete (node:fs:188:23)
Node.js v22.15.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

In the small window between these lines:
[2025-11-06T14:39:47.366] [INFO] default - default client is ready.
[2025-11-06T14:40:48.032] [INFO] default - Client default was logged out. Restarting...
I am able to send messages. But the callback to whatsapp of me linking a device doesn't seem to hold.

**Comment by PGayol** [comment]
Same issue here! Logs look also the same.

**Comment by jlabeeuw** [comment]
Same here too:

[2025-11-06T14:39:37.712] [INFO] default - Whatsapp Addon started.
[2025-11-06T14:39:38.100] [INFO] default - default require authentication over QRCode, please see your notifications...
[2025-11-06T14:39:47.366] [INFO] default - default client is ready.
[2025-11-06T14:40:48.032] [INFO] default - Client default was logged out. Restarting...
node:internal/fs/rimraf:59
    callback(err);
    ^
TypeError: callback is not a function
    at CB (node:internal/fs/rimraf:59:5)
    at FSReqCallback.oncomplete (node:fs:188:23)
Node.js v22.15.1
s6-rc: info: service legacy-services: stopping

Whatsapp is giving the message:
Couldn't log in. Check your phone
s Internet connection and scan the QR code again.
Tried on wifi and mobile data to ensure its not an issue with my add blocker

**Comment by kes-kus** [comment]
Same here, but I get an identical error when scanning a QR from green-api.com. I am afraid the failure is in the Whatsapp logic.

**Comment by Rafalll111** [comment]
Same here

**Comment by ShaylenIT** [comment]
Hi Everyone, 

I submitted a PR 5 months ago to resolve this but it hasn't been accepted yet.

You can use my fork in the meantime. Just uninstall the original first to avoid conflicts. Let me know if this works for you. 
https://github.com/ShaylenIT/ha-whatsapp-addon

**Comment by brggmn** [comment]
> Hi Everyone,
> 
> I submitted a PR 5 months ago to resolve this but it hasn't been accepted yet.
> 
> You can use my fork in the meantime. Just uninstall the original first to avoid conflicts. Let me know if this works for you. https://github.com/ShaylenIT/ha-whatsapp-addon

Hi @ShaylenIT 

Tried that already, not working either.

**Comment by ShaylenIT** [comment]
> > Hi Everyone,
> > 
> > I submitted a PR 5 months ago to resolve this but it hasn't been accepted yet.
> > 
> > You can use my fork in the meantime. Just uninstall the original first to avoid conflicts. Let me know if this works for you. https://github.com/ShaylenIT/ha-whatsapp-addon
> 
> Hi @ShaylenIT 
> 
> Tried that already, not working either. 

That's odd, mine still works but probably because I'm still logged in.
You can try this one also, it's just a bit resource intensive. 
https://github.com/gajosu/whatsapp-ha-addon

**Comment by virus100b** [comment]
Same here. 
It was working until i changed the phone. With the new phone is failing reading the qr code.

Tried with https://github.com/ShaylenIT/ha-whatsapp-addon, same result.
With this https://github.com/gajosu/whatsapp-ha-addon i manage to add but is disconnecting shortly and regenerates a new qr code.

**Comment by rvdheuvel72** [comment]
Today I receive a QRcode to link whatsapp again to HomeAssistant as I do every few weeks. Normally this goes smooth, but this time when I scan the QRcode is comes up with a message "logging in..." on my phone, at the same time messages start to flow again, but the login times out after 1 or 2 minutes and service stops working again and showing a new QRcode to link again.

Tried several times, no luck.

**Comment by FrancoCarrozza** [comment]
The exact same thing happens to me too, I didn't realize that an issue had already been opened and I opened a new one, when I realized I closed it as a duplicate of this one.

**Looking for a possible working alternative I found this one which has a different implementation and for me it worked correctly:**

    https://github.com/gajosu/whatsapp-ha-addon

**Comment by rvdheuvel72** [comment]
Seems this is not a bug from the add-in, but a bug in WhatsApp!

I tried some other solutions and they also had issue with authentication, or losing their linked web devices.

My issues was resolved when I removed my dual account setup in WhatsApp on1 device and move my 2nd number to a separate phone.

**Comment by MaxLinSG** [comment]
Same thing happened :(

**Comment by kalhimeo** [comment]
yep I can confirm that they changed something, it's not possible to associate the account with the QR code anymore :-(

**Comment by brggmn** [comment]
> ...
> 
> My issues was resolved when I removed my dual account setup in WhatsApp on1 device and move my 2nd number to a separate phone.

Can you describe what you have done? I don't find anything pointing to these settings.

**Comment by lcsneil** [comment]
It IS possible to associate a web page (via browser) with the 2nd number (i.e. switch accounts) via QR code but does take much longer than the 1st number. Still doesnt work via the HA QR  code though. 

lcsneil

**Comment by Kalisnoir** [comment]
I just tried this for the first time and having the same issue - scanning the QR code time out on the app with "Couldn't log in. Check your phone's Internet connection and scan the QR code again.", here are the logs

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Whatsapp
 Whatsapp addon for send message from Home Assistant
-----------------------------------------------------------
 Add-on version: 1.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 16.3  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2025.11.3
 Home Assistant Supervisor: 2025.11.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:41:27] INFO: Installed custom component.
[2025-12-03T11:41:28.904] [INFO] default - Whatsapp Addon started.
[2025-12-03T11:41:29.442] [INFO] default - default require authentication over QRCode, please see your notifications...
[2025-12-03T11:42:29.484] [INFO] default - default require authentication over QRCode, please see your notifications...
[2025-12-03T11:42:44.287] [INFO] default - default client is ready.
[2025-12-03T11:43:44.318] [INFO] default - Client default was logged out. Restarting...
node:internal/fs/rimraf:59
    callback(err);
    ^
TypeError: callback is not a function
    at CB (node:internal/fs/rimraf:59:5)
    at FSReqCallback.oncomplete (node:fs:188:23)
Node.js v22.15.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by lcsneil** [comment]
Just to say that I now cant register with the main WhatsApp number. On Android you can have Main and second Number whatsapp and on each of those you can switch between two numbers (giving me the ability to have 4 WhatsApp numbers on the phone. Up until about a week ago I had all 4 on HA via QR code. As of about an hour ago the others have timed out and now I cant get it to Log in at all on any of the 4 numbers including the main 'first' number. 

I suspect it will be the same for everyone once your numbers time out and need a refresg. It's fine on a browser webpage with the QR code. 


lcsneil

**Comment by muten86** [comment]
Dear all, it seems, that this issue is known at bayleys and solutions are already proposed.
https://github.com/WhiskeySockets/Baileys/issues/2110

Is anybody able to build a working solution? I'm not capable of implementing this.

**Comment by daknightuk** [comment]
I have exactly the same problem although mine started this morning. I noted that on my PC whatapp web has signed me out on a different whatsapp account and now the whatsapp web process asks for the qr code to be scanned once (recognised in whatsapp as edge) then it asks a 2nd time to scan the qr code and then is recognised as Windows So I think its a LOGON FLOW issue related to changes that meta have made

**Comment by FelipeGlauber** [comment]
> The exact same thing happens to me too, I didn't realize that an issue had already been opened and I opened a new one, when I realized I closed it as a duplicate of this one.
> 
> **Looking for a possible working alternative I found this one which has a different implementation and for me it worked correctly:**
> 
> ```
> https://github.com/gajosu/whatsapp-ha-addon
> ```

Same problem here, so I came here to Github and tested this and I can confirm, it works!
> https://github.com/gajosu/whatsapp-ha-addon

It seems to be best maintained at the moment so I replaced this solution by the /gajosu one.

**Comment by hvannieu** [comment]
Unfortunately, the same issue is happening here. Is there any sight of a fix for this yet?

**Comment by TadFocus** [comment]
Will this issue be fixed, or should I look for a solution in another repository?

**Comment by ShaylenIT** [comment]
Hi All,

I've resolved the issue on my folk; you can install it here. https://github.com/ShaylenIT/ha-whatsapp-addon
You will need to uninstall your current add-on the prevent conflicts.

I'll submit a PR, however, my previous PR wasn't accepted since June 2025

**Comment by brggmn** [comment]
> Hi All,
> 
> I've resolved the issue on my folk; you can install it here. https://github.com/ShaylenIT/ha-whatsapp-addon You will need to uninstall your current add-on the prevent conflicts.
> 
> I'll submit a PR, however, my previous PR wasn't accepted since June 2025

I can confirm this update works and resolved my problem!

**Comment by FaserF** [comment]
Works also at my integration, if anyone still has this issue; https://faserf.github.io/ha-whatsapp/
